name: Release to Packagist

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - name: Install Composer
        run: curl -sS https://getcomposer.org/installer | php

      - name: Publish to Packagist
        run: |
          composer config --global github-oauth.github.com ${{ secrets.GITHUB_TOKEN }}
          composer validate
          composer publish --token ${{ secrets.PACKAGIST_API_KEY }}
